name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn[standard] onnxruntime numpy pillow python-multipart httpx

      - name: Run unit tests
        run: |
          python -m unittest discover -s HumanCheckerBackend/tests -p "test_*.py" -v